<?php

namespace AppBundle\Repository;

/**
 * AgencertfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencertfRepository extends \Doctrine\ORM\EntityRepository
{
}
