<?php

namespace AppBundle\Repository;

/**
 * ArrondissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrondissementRepository extends \Doctrine\ORM\EntityRepository
{
}
