<?php

namespace AppBundle\Repository;

/**
 * Bac_selectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Bac_selectionRepository extends \Doctrine\ORM\EntityRepository
{
}
