<?php

namespace AppBundle\Repository;

/**
 * BacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BacRepository extends \Doctrine\ORM\EntityRepository
{
}
