<?php

namespace AppBundle\Repository;

/**
 * Cycle_etablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cycle_etablissementRepository extends \Doctrine\ORM\EntityRepository
{
}
