<?php

namespace AppBundle\Repository;

/**
 * Diplome_coachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Diplome_coachRepository extends \Doctrine\ORM\EntityRepository
{
}
