<?php

namespace AppBundle\Repository;

/**
 * Ecole_supRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ecole_supRepository extends \Doctrine\ORM\EntityRepository
{
}
