<?php

namespace AppBundle\Repository;

/**
 * Epreuve_bacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Epreuve_bacRepository extends \Doctrine\ORM\EntityRepository
{
}
