<?php

namespace AppBundle\Repository;

/**
 * FlashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlashRepository extends \Doctrine\ORM\EntityRepository
{
}
