<?php

namespace AppBundle\Repository;

/**
 * Offre_formationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Offre_formationRepository extends \Doctrine\ORM\EntityRepository
{
}
