<?php

namespace AppBundle\Repository;

/**
 * Ouvrage_programmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ouvrage_programmeRepository extends \Doctrine\ORM\EntityRepository
{
}
