<?php

namespace AppBundle\Repository;

/**
 * PubtiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubtiersRepository extends \Doctrine\ORM\EntityRepository
{
}
