<?php

namespace AppBundle\Repository;

/**
 * PubvipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubvipRepository extends \Doctrine\ORM\EntityRepository
{
}
